osscar-org/scicode-widgets

- pyproject.toml
It comes to clashes in formatting between isort and black otherwise (see https://stackoverflow.com/q/76038513)
----
:books: Documentation preview :books:: https://scicode-widgets--13.org.readthedocs.build/en/13/
> Set isort profile to black

- src/scwidgets/__init__.py
I am not sure why this is not invoked, but in the PR https://github.com/osscar-org/scicode-widgets/pull/12 I got the linter error
https://www.flake8rules.com/rules/W504.html
----
:books: Documentation preview :books:: https://scicode-widgets--15.org.readthedocs.build/en/15/
> Fixing W504 in __init__.py

- src/scwidgets/check/__init__.py
- src/scwidgets/check/_widget_check_registry.py
- tests/notebooks/widget_check_registry.py
- tests/test_check.py
- tests/test_widgets.py
The CheckRegistry is more or less the same, just that the management of check results (now in form of an Exception or a ChecksLog) is handled in a more structural manner. What helps here a lot is that CheckLogs handles the way the message is converted to a string.
The CheckableWidget base class manages now most of the check logic (or rather it forwards to the CheckRegistry). The result of the results is responsibility of the inherited class.
----
:books: Documentation preview :books:: https://scicode-widgets--12.org.readthedocs.build/en/12/
> Add Check Registry class

- .codecov.yml
- .github/workflows/tests.yml
- src/scwidgets/cue/_widget_reset_cue_button.py
- tests/notebooks/widget_check_registry.py
- tests/notebooks/widgets_cue.py
- tox.ini
One big problem with the coverage is that the tests for the widgets are not recorded by the coverage. First I thought this is just because they are executed within a subprocess for which coverage has a solution https://coverage.readthedocs.io/en/latest/subprocess.html, but it is actually more related to how python code is executed in a notebook. There exist a package `pytest-notebook` that supports coverage for notebooks, but I could not get it merge with our framework without much extra effort. In the end it also cannot record the code that is executed when using selenium to pass user interactions (e.g. button clicks), because it uses nbclient that runs the notebook a different execution context (which AFAIK does not really load UI elements). So I will just run the python scripts that …
> Add coverage

- pyproject.toml
- src/scwidgets/check/_widget_check_registry.py
- src/scwidgets/code/__init__.py
- src/scwidgets/code/_widget_code_demo.py
- src/scwidgets/code/_widget_code_input.py
- src/scwidgets/cue/_widget_cue_box.py
- tests/notebooks/widget_check_registry.py
- tests/notebooks/widget_code_demo.py
- tests/test_check.py
- tests/test_code.py
- tests/test_widgets.py
CodeInput is a wrapper around WidgetCodeInput that also accepts a function as input
TODO:
----
:books: Documentation preview :books:: https://scicode-widgets--17.org.readthedocs.build/en/17/
> Add CodeDemo and CodeInput

- src/scwidgets/code/_widget_code_demo.py
- src/scwidgets/css/widgets.css
- src/scwidgets/cue/__init__.py
- src/scwidgets/cue/_widget_cue.py
- src/scwidgets/cue/_widget_cue_box.py
- src/scwidgets/cue/_widget_reset_cue_button.py
- tests/notebooks/widgets_cue.py
- tests/test_widgets.py
- tox.ini
Now CueBox and ResetCueButton inherit from CueWidget. This implements cueing behavior for ResetCueButton.
----
:books: Documentation preview :books:: https://scicode-widgets--27.org.readthedocs.build/en/27/
> Cue behavior is moved to new class CueWidget

- pyproject.toml
- src/scwidgets/_utils.py
- src/scwidgets/answer/__init__.py
- src/scwidgets/answer/_widget_answer_registry.py
- src/scwidgets/check/_widget_check_registry.py
- src/scwidgets/code/_widget_code_demo.py
- src/scwidgets/code/_widget_parameter_panel.py
- src/scwidgets/css/widgets.css
- src/scwidgets/exercise/__init__.py
- src/scwidgets/exercise/_widget_textarea.py
- tests/notebooks/widget_answers.py
- tests/test_answer.py
- tests/test_widgets.py
* New class exercise.Textarea that implements AnswerWidget
* CodeDemo implements AnswerWidget
* CodeDemo: merge member functions handle_checks_result and _output_results
* add _utils.py with Printer static class for nicer printing using termcolor
* replace prints with Printer.print_* functions
* adapt save css style to more readable
* parameters in ParameterPanel are now settable
----
📚 Documentation preview 📚: https://scicode-widgets--31.org.readthedocs.build/en/31/
> Implement AnswerRegistry and AnswerWidget

- .github/workflows/tests-lab-3.yml
- .github/workflows/tests-notebook-7.yml
- tests/conftest.py
- tests/test_widgets.py
- tox.ini
Tests take now a `JUPYTER_TYPE` that determines the if executed with jupyter lab or or notebook. By that the class names are determined. Previous tests can be now execued with the tox environment tests-notebook-7, the jupyter lab tests with tests-lab-3 tests. Tests have been extended where they needed to be to also work with jupyter lab.
----
📚 Documentation preview 📚: https://scicode-widgets--32.org.readthedocs.build/en/32/
> Add jupyter lab 3.6.5 tests

- src/scwidgets/code/_widget_code_demo.py
- tests/notebooks/widget_code_demo.py
- tests/test_code.py
- tests/test_widgets.py
----
📚 Documentation preview 📚: https://scicode-widgets--33.org.readthedocs.build/en/33/
> CodeDemo does now work with None parameters if update_func is given

- src/scwidgets/answer/_widget_answer_registry.py
- src/scwidgets/code/_widget_code_demo.py
- src/scwidgets/css/widgets.css
- src/scwidgets/exercise/_widget_textarea.py
- tests/test_widgets.py
This allows to add a preamble to the CodeDemo and exercise.Textarea by the argument exercise_description. The answer key is used as title if None is given.
----
📚 Documentation preview 📚: https://scicode-widgets--35.org.readthedocs.build/en/35/
> Add exercise description and title

- tests/test_widgets.py
Sometimes in jupyter lab 5 canvases exist, one is not displayable and can be ignored. In this fix we filter out all canvases that are not displayable.
----
📚 Documentation preview 📚: https://scicode-widgets--36.org.readthedocs.build/en/36/
> Fix jupyter lab wrong number of of matplotlib canvases

- src/scwidgets/code/__init__.py
- src/scwidgets/code/_widget_parameter_panel.py
- src/scwidgets/exercise/__init__.py
- src/scwidgets/exercise/_widget_code_exercise.py
- src/scwidgets/exercise/_widget_text_exercise.py
- tests/notebooks/widget_answers.py
- tests/notebooks/widget_code_exercise.py
- tests/test_code.py
- tests/test_widgets.py
* rename Textarea TextExercise
* move CodeDemo to exercise and name CodeExercise
----
📚 Documentation preview 📚: https://scicode-widgets--39.org.readthedocs.build/en/39/
> Restructure exercise submodule

- .github/workflows/tests-lab-4.yml
- pyproject.toml
- src/scwidgets/cue/_widget_cue_figure.py
- tests/conftest.py
- tests/test_widgets.py
- tox.ini
Upgrade to widget_code_input version 4 and tests for lab 4
----
📚 Documentation preview 📚: https://scicode-widgets--45.org.readthedocs.build/en/45/
> Upgrading to widget-code-input 4 and adding tests for lab 4

- tests/test_widgets.py
- tox.ini
See commit messages.
----
📚 Documentation preview 📚: https://scicode-widgets--55.org.readthedocs.build/en/55/
> Some clean up for PR #45

- src/scwidgets/code/_widget_code_input.py
- tests/conftest.py
- tests/notebooks/widget_scwidgets_code_input.py
- tests/test_code.py
- tests/test_widgets.py
Fix for #53
----
📚 Documentation preview 📚: https://scicode-widgets--54.org.readthedocs.build/en/54/
> Fixing unlinked traits in WCI due to invalid `code_theme` (Fix #53)

- src/scwidgets/cue/_widget_cue_figure.py
The figure widget has toolbar that is now by default disabled in the CueFigure.
----
📚 Documentation preview 📚: https://scicode-widgets--56.org.readthedocs.build/en/56/
> Core: Add `no_toolbar` option to CueFigure

- src/scwidgets/exercise/_widget_code_exercise.py
- tests/test_code.py
- tox.ini
When the code is None in the CodeExercise and a ExerciseRegistry is given, then an error is raised when the save cue box is created, because the cue_widget is None. Since the cue widgets are set later on, we use a dummy widget on initialization with is later replaced.
----
📚 Documentation preview 📚: https://scicode-widgets--57.org.readthedocs.build/en/57/
> Fix code is None in CodeExercise with ExerciseRegistry 

- src/scwidgets/check/_check.py
- src/scwidgets/exercise/_widget_code_exercise.py
When the the update does not print anything the output is not cleared, since it waits for an output to be cleared. We fix this by printing an empty string to invoke the clearning of the output
----
📚 Documentation preview 📚: https://scicode-widgets--60.org.readthedocs.build/en/60/
> Fix nonclearing output when nothing is outputed

- src/scwidgets/check/__init__.py
- src/scwidgets/check/_check.py
- src/scwidgets/check/_widget_check_registry.py
- src/scwidgets/exercise/_widget_code_exercise.py
- tests/test_check.py
- tests/test_code.py
When multiple checks were handled only the output of the last check remained. This is because all checks were individually handled and each handling cleared the output. We now collect the check result including the exceptions and then send it for handling.
----
📚 Documentation preview 📚: https://scicode-widgets--64.org.readthedocs.build/en/64/
> Results of checks are now collected before handling

- src/scwidgets/check/_asserts.py
We divided by zero when the reference value was zero. We now take the max of both absolute values
----
📚 Documentation preview 📚: https://scicode-widgets--63.org.readthedocs.build/en/63/
> Fix assert_numpy_allclose for zeros in relative error computation

- src/scwidgets/code/_widget_code_input.py
- tests/test_code.py
When an exception is thrown within a WCI, the last frame is used as context to add the input lines. This does not work if the exception is thrown within a function within WCI. Therefore we now iterate through all traceback frames to find the one corresponding to WCI.
The corresponding PR in WCI https://github.com/osscar-org/widget-code-input/pull/26 to solve it there.
----
📚 Documentation preview 📚: https://scicode-widgets--62.org.readthedocs.build/en/62/
> Fix for nested errors are not correctly resolved

- src/scwidgets/check/__init__.py
- src/scwidgets/check/_asserts.py
- tests/test_check.py
Asserts equality between two objects
----
📚 Documentation preview 📚: https://scicode-widgets--65.org.readthedocs.build/en/65/
> Add `assert_equal` to asserts

- src/scwidgets/exercise/_widget_code_exercise.py
- tests/test_code.py
The `update_func` required an argument for the code exercise. With this commit `update_func` does not need to take any argument which supports a usage using globals.
----
📚 Documentation preview 📚: https://scicode-widgets--66.org.readthedocs.build/en/66/
> Support `update_func` without arguments in `CodeExercise`

- src/scwidgets/code/_widget_code_input.py
- tests/test_code.py
The function wrapping the `CodeInput` can now be used by calling the `CodeInput` instance.
----
📚 Documentation preview 📚: https://scicode-widgets--68.org.readthedocs.build/en/68/
> Add `__call__` to `CodeInput` for easier usage

- src/scwidgets/code/_widget_parameter_panel.py
- src/scwidgets/exercise/_widget_code_exercise.py
- tests/test_code.py
This effects the classes `CodeExercise` and `ParameterPanel`
> Change API `parameters` to `params`

- src/scwidgets/exercise/_widget_code_exercise.py
- tests/test_code.py
`cue_outputs` has been changed to `outputs`.
The `CodeExercice` has a new property `output` which is the first element of `outputs`:.
Now non `CueOutput` objects can be passed that are converted to `CueFigure` or `CueObject` depending on the type.
----
📚 Documentation preview 📚: https://scicode-widgets--71.org.readthedocs.build/en/71/
> Change API in `CodeExercise` related to `cue_outputs`

- src/scwidgets/check/_widget_check_registry.py
- tests/test_widgets.py
By not using the title formatting and using symbols a better overview is given.
----
📚 Documentation preview 📚: https://scicode-widgets--69.org.readthedocs.build/en/69/
> Improve formatting of all widgets being checked

- src/scwidgets/__init__.py
- src/scwidgets/_css_style.py
- src/scwidgets/check/_widget_check_registry.py
- src/scwidgets/exercise/_widget_code_exercise.py
- src/scwidgets/exercise/_widget_exercise_registry.py
- src/scwidgets/exercise/_widget_text_exercise.py
- tests/notebooks/widget_answers.py
- tests/notebooks/widget_check_registry.py
- tests/notebooks/widget_code_exercise.py
- tests/notebooks/widget_scwidgets_code_input.py
- tests/test_widgets.py
To avoid that the user needs to explicitely load a cell with the style the style is injected into the widgets. Since `CueOutput` does offer an easy way to inject the style the widgets inheriting from `CueWidget` still require an explicit dipslay of the style.
----
📚 Documentation preview 📚: https://scicode-widgets--73.org.readthedocs.build/en/73/
> Inject css style into widgets

- src/scwidgets/check/_check.py
- src/scwidgets/check/_widget_check_registry.py
- tests/test_check.py
For some checks the teacher might want to check behavior of the students code. In this code no inputs are needed.
TODO: test
----
📚 Documentation preview 📚: https://scicode-widgets--67.org.readthedocs.build/en/67/
> Allow checks with no inputs for property-based testing

- src/scwidgets/check/_check.py
- src/scwidgets/exercise/_widget_code_exercise.py
- tests/test_code.py
----
📚 Documentation preview 📚: https://scicode-widgets--74.org.readthedocs.build/en/74/
> Various cleanups and fixes

- src/scwidgets/exercise/_widget_code_exercise.py
- tests/notebooks/widget_code_exercise.py
- tests/test_code.py
- tests/test_widgets.py
When no code input exists the update button should be only shown for update_mode manual.
----
📚 Documentation preview 📚: https://scicode-widgets--61.org.readthedocs.build/en/61/
> Only create update button when update_mode manual or code input is not None

- src/scwidgets/cue/_widget_cue_figure.py
We do the same as for the inline backend.
Also improve the error message to suggest using "widget" backend.
----
📚 Documentation preview 📚: https://scicode-widgets--76.org.readthedocs.build/en/76/
> Support matplotlib backend "macosx" for `CueFigure`

- src/scwidgets/cue/_widget_cue_figure.py
"agg" is the terminal Linux backend, since the user should be aware that nothing can be shown in this case and raising an error prevents testing certain functionalities, we support it and do the same commands as for the "inline" backend.
----
📚 Documentation preview 📚: https://scicode-widgets--78.org.readthedocs.build/en/78/
> Support matplotlib backend "agg" for `CueFigure`

- src/scwidgets/cue/_widget_cue_figure.py
- src/scwidgets/exercise/_widget_code_exercise.py
- tests/test_code.py
If one output is only given that is translated to a `CueFigure` then it can be accessed with `code_exercise.figure` instead of `code_exercise.output.figure`
----
📚 Documentation preview 📚: https://scicode-widgets--77.org.readthedocs.build/en/77/
> Make figure directly accessible through `CodeExercise`

- src/scwidgets/exercise/_widget_code_exercise.py
- tests/test_widgets.py
To enforce `clear_output` even when the update is not printing anything we used `print("", end"")` this seems not to always work so we print an empty char now.
----
📚 Documentation preview 📚: https://scicode-widgets--80.org.readthedocs.build/en/80/
> Print empty char after updated code exercise

- src/scwidgets/exercise/_widget_code_exercise.py
- tests/notebooks/widget_answers.py
- tests/test_code.py
Since the property has been changed to `params`, it makes sense to also change the initialization argument to it.
> Change `CodeExercise` init `parameters` to `params`

- src/scwidgets/code/_widget_code_input.py
- src/scwidgets/exercise/_widget_code_exercise.py
Rename `get_function_object` to `wrapped_function` and make it property to be more consistent with the `function`.
In `__call__` the wrapped function is now called, this way `__call__` replaces `run` function that is removed as a consequence.
----
📚 Documentation preview 📚: https://scicode-widgets--84.org.readthedocs.build/en/84/
> Make `CodeInput` naming related to the function object more consistent

- src/scwidgets/exercise/_widget_code_exercise.py
- tests/test_code.py
This way the meaning of the `run_update` function should be clearer and is less to type.
----
📚 Documentation preview 📚: https://scicode-widgets--85.org.readthedocs.build/en/85/
> In `CodeExercise` rename `update_func` to `update`

- src/scwidgets/exercise/_widget_code_exercise.py
- tests/test_code.py
Because the `exercise_key` is used for the `ExerciseRegistry` and the `CheckRegistry` we need to ensure the `CodeExercise` can be run with each individual one and both.
----
📚 Documentation preview 📚: https://scicode-widgets--88.org.readthedocs.build/en/88/
> Fix usage of `exercise_key` without `ExerciseRegistry`

- .github/workflows/publish-pypi.yml
- pyproject.toml
- src/scwidgets/__init__.py
Also updates minium required python version, description and location of the LICENSE file in pyproject.toml
----
📚 Documentation preview 📚: https://scicode-widgets--87.org.readthedocs.build/en/87/
> Add workflow for publishing to pypi

- src/scwidgets/code/_widget_code_input.py
- tests/test_code.py
The problem with inspect is that ignores the actual formatting provided by the user and that it sometimes stores directly the related objects (e.g. type annotation `x: int` stores the type `int` instead of the string `int` which makes it hard to pass as string later on). With `ast` this should be resolved. See example
```python
def mock_function_1(x: int, y: int):
"""
This is an example function.
It adds two numbers.
"""
if x > 0:
return x + y
else:
return y
import ast, inspect
module = ast.parse(inspect.getsource(mock_function_1))
ast.dump(module)
#Out: "Module(body=[FunctionDef(name='mock_function_1', args=arguments(posonlyargs=[], args=[arg(arg='x', annotation=Name(id='int', ctx=Load())), arg(arg='y', annotation=Name(id='int', ctx=Load()))], kwonlyargs=[], kw_defaults=[], defaults=[]), …
```
> Refactor parsing of function in `CodeInput` using `ast`

- src/scwidgets/code/_widget_code_input.py
- tests/test_code.py
This allows one to update the builtins variables when compiling the code which is necessary when the teacher wants to provide variables to the code that do not need to be created by the student.
----
📚 Documentation preview 📚: https://scicode-widgets--91.org.readthedocs.build/en/91/
> Add init argument `builtins` to `CodeInput`

- src/scwidgets/code/_widget_code_input.py
- tests/test_code.py
This removes the linebreak at the end of the code in the `CodeInput` which was undesired formatting.
> Strip function body of `CodeInput`

- src/scwidgets/cue/_widget_cue_object.py
- tests/test_code.py
Shortens the name for usage and it is clearer is it is derived from the name of the class.
----
📚 Documentation preview 📚: https://scicode-widgets--96.org.readthedocs.build/en/96/
> Rename from `CueObject` the `display_object` to `object`

- src/scwidgets/cue/_widget_cue_figure.py
The negation in the variable makes it less unintuitive to use.
----
📚 Documentation preview 📚: https://scicode-widgets--95.org.readthedocs.build/en/95/
> Rename in `CueFigure` the `no_toolbars` to `show_toolbars`

- src/scwidgets/exercise/_widget_code_exercise.py
When a CodeExercise with parameters is created and a figure is created the `<Figure size 640x480 with 0 Axes>` is displayed. This is prevented by closing the figure when `CueFigure` is created. I am not sure why this happens. It could be related to interact. It can be fixed by moving the CueFigure creation before the ParameterPanel creation.
----
📚 Documentation preview 📚: https://scicode-widgets--94.org.readthedocs.build/en/94/
> Fix figure not properly closed in CodeExercise with parameters

- src/scwidgets/cue/_widget_cue.py
- src/scwidgets/cue/_widget_cue_box.py
- src/scwidgets/cue/_widget_cue_figure.py
- src/scwidgets/cue/_widget_cue_object.py
- src/scwidgets/cue/_widget_cue_output.py
- src/scwidgets/exercise/_widget_code_exercise.py
mypy cannot infer the correct type of traits_to_observe in CueWidget init constructor after if checks so we ignore it. Further there are problems with types of List[A | B] when wants to assign them with a variable of type List[A]. We ignore these cases too.
Fix types from `Union[List[str], List[Sentinel], List[List[str]]]` to `List[Union[str, Sentinel, List[str]]]`.
----
📚 Documentation preview 📚: https://scicode-widgets--98.org.readthedocs.build/en/98/
> Ignore mypy errors related to CueWidget

- src/scwidgets/exercise/_widget_exercise_registry.py
- tests/test_answer.py
Adds function `load_answer_from_student_name` and `load_answer_from_loaded_file` to ExerciseRegistry API. `load_answer_from_loaded_file` does what `load_answer` did before. `load_answer` requires now an additional argument an `answers_filename`. `load_answer_from_student_name` allows to load specific answers without loading the entire file which can conflict with entries that do not have yet a corresponding widget.
----
📚 Documentation preview 📚: https://scicode-widgets--100.org.readthedocs.build/en/100/
> Add load specific answer from answer file using student name

- src/scwidgets/exercise/_widget_exercise_registry.py
Exercise filename lowered and spaces are replaced with underscores.
----
📚 Documentation preview 📚: https://scicode-widgets--101.org.readthedocs.build/en/101/
> Change exercise filename standardization

- src/scwidgets/code/_widget_parameter_panel.py
- src/scwidgets/exercise/_widget_code_exercise.py
- tests/test_code.py
Introduce `param_to_widget_map` to access the widgets in form of a dict for more convenient handling.
To more robustly set parameter values the setter has been replaced by the `update_params` method. The setter introduced behavior that is unintuitive for python as it behaves like an update function while using assign syntax.
Alternatively a design implementing methods `__{get,set}item__`, `values` and `keys` was considered, but `keys` was clashing with the trait variable of `Widget` which would have required a different naming. This would have been more confusing.
```python
code_ex.params # returns parameter_panel
code_ex.params['x'] = 5 # works, updates the panel
code_ex.params['x']
code_ex.params.values() # works
code_ex.params.params_keys() # cannot be keys because it is already used …
```
> Restructure storage of parameters and widgets in `ParameterPanel`

- src/scwidgets/code/_widget_parameter_panel.py
- src/scwidgets/exercise/_widget_code_exercise.py
- tests/notebooks/widget_answers.py
- tests/test_code.py
The initial suggestion was to use `params` for the parameter dict and `parameters` for the parameter panel widget. I found however the usage of `parameters` for the panel confusing so I would not go with this suggestion. The abbreviation is therefore not needed anymore.
----
📚 Documentation preview 📚: https://scicode-widgets--104.org.readthedocs.build/en/104/
> Rename params to parameters

- src/scwidgets/exercise/_widget_code_exercise.py
- src/scwidgets/exercise/_widget_text_exercise.py
- tests/notebooks/widget_answers.py
- tests/test_code.py
`exercise_key` to `key`
`exercise_description` to `description`
`exercise_title` to `title`
----
📚 Documentation preview 📚: https://scicode-widgets--108.org.readthedocs.build/en/108/
> Rename exercise widgets related member variables

- README.rst
- docs/src/nbgrader.ipynb
----
📚 Documentation preview 📚: https://scicode-widgets--110.org.readthedocs.build/en/110/
> Update mybinder link in nbgrader.ipynb

- tests/test_code.py
In case the tests fail after the creation of the file but before the remove, the file still is not removed and will make the test fail in the next run.
----
📚 Documentation preview 📚: https://scicode-widgets--83.org.readthedocs.build/en/83/
> Put the remove in `test_save_registry` in try-finally block

- src/scwidgets/check/_widget_check_registry.py
- tests/notebooks/widget_check_registry.py
- tests/test_widgets.py
For students this is confusing, since the might overwrite the references, so there needs to be an option to disable it. Disabling it by default is a bit randomly chosen, but having less code in the student version of the code is the idea.
----
📚 Documentation preview 📚: https://scicode-widgets--44.org.readthedocs.build/en/44/
> Display by default not the `set_all_references_button` in the CheckRegistry

- .github/workflows/build-docs.yml
Until the the readthedocs hook is fixed we use this workflow to verify the doc.
----
📚 Documentation preview 📚: https://scicode-widgets--112.org.readthedocs.build/en/112/
> Add build docs github workflow

- .github/workflows/build-docs.yml
In PR #112 I pushed a workflow with syntax errors, because it was not shown in the PR I thought I needed to first push so the PR gets active but it was just that workflows with syntax errors are not even shown in the PR. One has to go to actions.
----
📚 Documentation preview 📚: https://scicode-widgets--114.org.readthedocs.build/en/114/
> Fix syntax errors in the docs workflow

- docs/src/check.ipynb
Replace old usage of `get_function_object()(...)` with `code(...)`
Remove section that refers how to compute output for a check because it can be now just done with `code_ex.code()`.
Remove widget that raises error since it is confusing what is meant. The connection with the check registry is not made.
> Update the check notebook

- src/scwidgets/exercise/_widget_code_exercise.py
The run button was still displayed in this case but could only work in case the code does not require any arguments. To enable the update button one needs now to at least provide parameters (empty in case when no parameters are needed). This enables the teacher to create exercises that are only checkable.
----
📚 Documentation preview 📚: https://scicode-widgets--115.org.readthedocs.build/en/115/
> Disable run button if no update function and parameters are given

- docs/src/check.ipynb
- docs/src/developers.rst
- docs/src/exercises.ipynb
- docs/src/getting_started.ipynb
- docs/src/nbgrader.ipynb
- src/scwidgets/check/_asserts.py
- src/scwidgets/check/_check.py
- src/scwidgets/check/_widget_check_registry.py
- src/scwidgets/code/_widget_code_input.py
- src/scwidgets/code/_widget_parameters_panel.py
- src/scwidgets/css_style.py
- src/scwidgets/cue/_widget_cue.py
- src/scwidgets/cue/_widget_cue_box.py
- src/scwidgets/cue/_widget_cue_figure.py
- src/scwidgets/cue/_widget_cue_object.py
- src/scwidgets/cue/_widget_cue_output.py
- src/scwidgets/cue/_widget_reset_cue_button.py
- src/scwidgets/exercise/_widget_code_exercise.py
- src/scwidgets/exercise/_widget_exercise_registry.py
- src/scwidgets/exercise/_widget_text_exercise.py
Initial run through the docs to fix typos and clear unclear moments
----
📚 Documentation preview 📚: https://scicode-widgets--125.org.readthedocs.build/en/125/
> Cleanup RTD and docstrings in src

- docs/src/exercises.ipynb
- src/scwidgets/exercise/__init__.py
- src/scwidgets/exercise/_widget_multiplechoice_exercise.py
This PR adds multiple-choice question capabilities to scicode-widgets, as discussed in #120.
The `SelectMultiple` is a bit ugly, if needed, we might need to do smth a bit more cosmetically pleasing. I couldn't find it in the ipywidgets, so we might have to implement it ourselves
----
📚 Documentation preview 📚: https://scicode-widgets--121.org.readthedocs.build/en/121/
> Adding MCQ

- README.rst
The dynamic links do not work in the RTD so we switch to raw links.
----
📚 Documentation preview 📚: https://scicode-widgets--129.org.readthedocs.build/en/129/
> Use github raw link for gifs
