- .github/workflows/deploy-jupyterlite.yml
- examples/requirements-jupyterlite.txt
- examples/requirements-notebooks.txt
- examples/requirements.txt
- repl/jupyter-lite.json
----
:books: Documentation preview :books:: https://scicode-widgets--5.org.readthedocs.build/en/5/
> Adding Jupyerlite support

- .github/workflows/lint.yml
- docs/src/conf.py
- tox.ini
----
:books: Documentation preview :books:: https://scicode-widgets--8.org.readthedocs.build/en/8/
> Add formater and linter

- .gitignore
- pyproject.toml
- src/scwidgets/__init__.py
- src/scwidgets/_widget_cue_box.py
- src/scwidgets/css/widgets.css
- tests/notebooks/widget_cue_box.py
- tests/test_widgets.py
* add css styles and function that sets them
* add tests for widget cue box
----
:books: Documentation preview :books:: https://scicode-widgets--9.org.readthedocs.build/en/9/
> Add cue box

- CONTRIBUTING.rst
- docs/src/index.rst
- tests/conftest.py
- tox.ini
* make webdriver argument "headless" optional using tox 
* add CONTRIBUTING.rst with instructions
----
:books: Documentation preview :books:: https://scicode-widgets--14.org.readthedocs.build/en/14/
> Add CONTRIBUTING.rst 

- tests/conftest.py
- tests/test_widgets.py
- tox.ini
See commit messages, they are quite verbose in explanation
----
:books: Documentation preview :books:: https://scicode-widgets--21.org.readthedocs.build/en/21/
> Improve selenium test integrity

- tests/conftest.py
This makes life a bit easier when debugging
----
:books: Documentation preview :books:: https://scicode-widgets--19.org.readthedocs.build/en/19/
> increase selenium driver window size to 1280x1024

- src/scwidgets/code/__init__.py
- src/scwidgets/code/_widget_code_demo.py
- src/scwidgets/code/_widget_code_input.py
- src/scwidgets/code/_widget_parameter_panel.py
- src/scwidgets/cue/_widget_cue_box.py
- src/scwidgets/cue/_widget_reset_cue_button.py
- tests/notebooks/widget_code_demo.py
- tests/test_check.py
- tests/test_code.py
- tests/test_widgets.py
- tox.ini
This uses the ipywidgets interactive feature for the parameter panel. I  have put a temporary ipynb demo into this PR.
----
:books: Documentation preview :books:: https://scicode-widgets--23.org.readthedocs.build/en/23/
> Add parameter panel

- pyproject.toml
- src/scwidgets/__init__.py
- src/scwidgets/check/_asserts.py
- src/scwidgets/check/_widget_check_registry.py
- src/scwidgets/code/_widget_code_demo.py
- src/scwidgets/code/_widget_code_input.py
- src/scwidgets/code/_widget_parameter_panel.py
- tests/test_code.py
The commits are quite verbose. Most of the commits are unrelated to each other
----
:books: Documentation preview :books:: https://scicode-widgets--24.org.readthedocs.build/en/24/
> Bunch of small fixes and changes

- src/scwidgets/check/_widget_check_registry.py
- src/scwidgets/code/_widget_code_demo.py
- src/scwidgets/code/_widget_parameter_panel.py
- src/scwidgets/css/widgets.css
- tests/notebooks/widget_code_demo.py
- tests/test_code.py
- tests/test_widgets.py
update_mode determines how the output is refreshed on a parameter change in the parameter panel. 
----
:books: Documentation preview :books:: https://scicode-widgets--28.org.readthedocs.build/en/28/
> Add update_mode to CodeDemo

- src/scwidgets/cue/_widget_cue_object.py
----
📚 Documentation preview 📚: https://scicode-widgets--34.org.readthedocs.build/en/34/
> Change draw_display behavior of CueObject

- src/scwidgets/_utils.py
- src/scwidgets/answer/_widget_answer_registry.py
- src/scwidgets/check/_check.py
- src/scwidgets/check/_widget_check_registry.py
- src/scwidgets/code/_widget_code_demo.py
- src/scwidgets/exercise/_widget_textarea.py
* remove print_* functions
----
📚 Documentation preview 📚: https://scicode-widgets--37.org.readthedocs.build/en/37/
> Rename Printer to Formatter

- src/scwidgets/check/__init__.py
- src/scwidgets/check/_check.py
- src/scwidgets/check/_widget_check_registry.py
- src/scwidgets/code/_widget_code_demo.py
- tests/test_check.py
- tests/test_code.py
----
📚 Documentation preview 📚: https://scicode-widgets--38.org.readthedocs.build/en/38/
> Rename ChecksLog to ChecksResult

- src/scwidgets/check/_asserts.py
- src/scwidgets/check/_check.py
----
📚 Documentation preview 📚: https://scicode-widgets--40.org.readthedocs.build/en/40/
> Fixes for formatting bugs in AssertResult messages

- src/scwidgets/code/_widget_code_input.py
- src/scwidgets/code/_widget_parameter_panel.py
- src/scwidgets/exercise/_widget_code_exercise.py
- tests/test_code.py
Various small changes all explained in each commit message
----
📚 Documentation preview 📚: https://scicode-widgets--41.org.readthedocs.build/en/41/
> Various small changes in CodeExercise, ParameterPanel and CodeInput

- src/scwidgets/answer/__init__.py
- src/scwidgets/exercise/__init__.py
- src/scwidgets/exercise/_widget_code_exercise.py
- src/scwidgets/exercise/_widget_exercise_registry.py
- src/scwidgets/exercise/_widget_text_exercise.py
- tests/notebooks/widget_answers.py
- tests/test_answer.py
- tests/test_widgets.py
* AnswerRegistry -> ExerciseRegistry
* AnswerWidget -> ExerciseWidget
* answer_key -> exercise_key
* answer_registry -> exercise_registry
----
📚 Documentation preview 📚: https://scicode-widgets--42.org.readthedocs.build/en/42/
> Move answer submodule to exercise submodule

- src/scwidgets/exercise/_widget_code_exercise.py
----
📚 Documentation preview 📚: https://scicode-widgets--79.org.readthedocs.build/en/79/
> Change default `update_mode` to "manual" in `CodeExercise`

- src/scwidgets/exercise/_widget_code_exercise.py
----
📚 Documentation preview 📚: https://scicode-widgets--97.org.readthedocs.build/en/97/
> Change | to Union usage to suport py39

- README.rst
----
📚 Documentation preview 📚: https://scicode-widgets--109.org.readthedocs.build/en/109/
> Update getting started link in README.rst

- src/scwidgets/exercise/_widget_code_exercise.py
For better readability.
----
📚 Documentation preview 📚: https://scicode-widgets--117.org.readthedocs.build/en/117/
> Add a linebreak between each check result

- src/scwidgets/__init__.py
----
📚 Documentation preview 📚: https://scicode-widgets--118.org.readthedocs.build/en/118/
> Release 0.1.0-dev1

- CHANGELOG.md
- src/scwidgets/__init__.py
----
📚 Documentation preview 📚: https://scicode-widgets--122.org.readthedocs.build/en/122/
> Release 0.1.0

- pyproject.toml
- tests/conftest.py
Update project urls and python versions
> Update metadata of repository

- README.rst
- Improve library description
- add link to nbgrader tutorial
- add installation instructions
----
📚 Documentation preview 📚: https://scicode-widgets--128.org.readthedocs.build/en/128/
> Restructure README

- docs/src/check.ipynb
- docs/src/exercises.ipynb
- docs/src/getting_started.ipynb
- docs/src/nbgrader.ipynb
----
📚 Documentation preview 📚: https://scicode-widgets--131.org.readthedocs.build/en/131/
> Add a note about LaTeX being not correctly rendered

- src/scwidgets/check/_widget_check_registry.py
----
📚 Documentation preview 📚: https://scicode-widgets--133.org.readthedocs.build/en/133/
> Pass argument `stop_on_assert_error_raised` from `add_check` to `Check`

- src/scwidgets/__init__.py
Includes the `MultipleChoiceExercise` and doc updates.
----
📚 Documentation preview 📚: https://scicode-widgets--134.org.readthedocs.build/en/134/
> Release `v0.2.0`
